apiVersion: v1
kind: ServiceAccount
metadata:
  name: unity-ads-metrics-ingestion
  labels:
    app.kubernetes.io/name: unity-ads-metrics-ingestion
    app.kubernetes.io/component: ingestion-api
    app.kubernetes.io/part-of: unity-ads
automountServiceAccountToken: false
